### ISSUE TITLE
1주차 과제: 아기 상어

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/PR-study-practice#3]
아기 상어 문제를 풀고 풀이를 업로드해주세요

**Comment by Seon-Ju** [comment]
저는 뚝심있게 체육복 문제를 풀었습니다
https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Programmers/%EC%B2%B4%EC%9C%A1%EB%B3%B5.py

**Comment by SoominRyu** [comment]
아기 상어 뚜루루뚜루
https://github.com/jungyoonoh/unit-study/blob/main/Soomin/Programmers/%EC%B2%B4%EC%9C%A1%EB%B3%B5.py

**Comment by jungyoonoh** [comment]
좋아요

**Comment by Seon-Ju** [comment]
> 좋아요

우왕

**Comment by jungyoonoh** [comment]
> 저는 뚝심있게 체육복 문제를 풀었습니다 https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Programmers/%EC%B2%B4%EC%9C%A1%EB%B3%B5.py

왜 그러셨죠?

**Comment by SoominRyu** [comment]
> 저는 뚝심있게 체육복 문제를 풀었습니다 https://github.com/Seon-Ju/unit-study/blob/main/Seonju/Programmers/%EC%B2%B4%EC%9C%A1%EB%B3%B5.py

체육복 좋아요

**Comment by jungyoonoh** [comment]
다시 문제가 생겼어요
